sudo: required
  services:
    - docker

  before_install:
    - docker build -t vikramhonsai/docker-react -f Dockerfile.dev .

  script:
    - docker run vikramhonsai/docker-react npm run test -- --coverage